# prediction

In [14]:
from absenteeism_module import *
model = absenteeism_model('model', 'scaler')
model.load_and_clean_data('Absenteeism_new_data.csv')
df_new_obs = model.predicted_outputs()
df_new_obs

/Users/sarah.nguyen/opt/anaconda3/lib/python3.7/site-packages/sklearn/base.py:306: UserWarning: Trying to unpickle estimator LogisticRegression from version 0.19.1 when using version 0.21.3. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
/Users/sarah.nguyen/opt/anaconda3/lib/python3.7/site-packages/sklearn/base.py:306: UserWarning: Trying to unpickle estimator StandardScaler from version 0.19.1 when using version 0.21.3. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)

,Reason_1,Reason_2,Reason_3,Reason_4,Month Value,Transportation Expense,Age,Body Mass Index,Education,Children,Pet,Probability,Prediction
0,0,0.0,0,1,6,179,30,19,1,0,0,0.122799,0
1,1,0.0,0,0,6,361,28,27,0,1,4,0.873392,1
2,0,0.0,0,1,6,155,34,25,0,2,0,0.268305,0
3,0,0.0,0,1,6,179,40,22,1,2,0,0.196385,0
4,1,0.0,0,0,6,155,34,25,0,2,0,0.723502,1
5,1,0.0,0,0,6,225,28,24,0,1,2,0.716891,1
6,1,0.0,0,0,6,118,46,25,0,2,0,0.570524,1
7,0,0.0,0,1,6,179,30,19,1,0,0,0.122799,0
8,0,0.0,0,1,6,118,37,28,0,0,0,0.134118,0
9,1,0.0,0,0,6,118,37,28,0,0,0,0.525007,1
10,0,0.0,0,1,6,378,36,21,0,2,4,0.454998,0
11,0,0.0,1,0,6,118,50,31,0,1,0,0.644742,1
12,0,0.0,1,0,6,233,31,21,1,1,8,0.351108,0
13,0,0.0,0,1,6,179,30,19,1,0,0,0.122799,0
14,0,0.0,0,0,6,235,48,33,0,1,5,0.096533,0
15,0,0.0,0,0,6,268,33,25,1,0,0,0.189479,0
16,0,0.0,1,0,6,118,50,31,0,1,0,0.644742,1
17,1,0.0,0,0,6,179,30,19,1,0,0,0.499738,0
18,0,0.0,0,1,6,291,40,25,0,1,1,0.389531,0
19,1,0.0,0,0,7,179,30,19,1,0,0,0.500161,1
20,0,0.0,0,1,7,118,37,28,0,0,0,0.134315,0
21,0,0.0,0,1,7,233,31,21,1,1,8,0.051367,0
22,1,0.0,0,0,7,118,37,28,0,0,0,0.525428,1
23,1,0.0,0,0,7,118,37,28,0,0,0,0.525428,1
24,0,0.0,0,1,7,233,31,21,1,1,8,0.051367,0
25,0,0.0,0,1,7,235,43,38,0,1,0,0.512352,1
26,0,0.0,1,0,7,233,31,21,1,1,8,0.351493,0
27,1,0.0,0,0,7,228,58,22,0,2,1,0.633385,1
28,0,0.0,0,1,7,118,37,28,0,0,0,0.134315,0
29,1,0.0,0,0,7,228,58,22,0,2,1,0.633385,1
30,0,0.0,0,1,7,189,33,25,0,2,2,0.244943,0
31,0,0.0,0,1,7,118,37,28,0,0,0,0.134315,0
32,0,0.0,0,1,7,361,28,27,0,1,4,0.491962,0
33,0,0.0,0,1,7,225,28,24,0,1,2,0.262240,0
34,1,0.0,0,0,7,369,31,25,0,3,0,0.966560,1
35,1,0.0,0,0,7,289,33,30,0,2,1,0.912399,1
36,1,0.0,0,0,7,235,37,29,1,1,1,0.746598,1
37,0,0.0,0,0,7,118,40,34,0,1,8,0.023090,0
38,0,0.0,0,0,7,231,39,35,0,2,2,0.295647,0
39,0,0.0,0,0,7,179,53,25,0,1,1,0.076450,0

# MySQL - Python connection

In [15]:
import pymysql

In [16]:
# connect to MySQL database - modify this when productize
# modify user and password for database access

conn = pymysql.connect(database = 'predicted_outputs', user = '', password = '')

In [17]:
# create cursor to write MySQL queries in Python IDE
cursor = conn.cursor()

In [18]:
# check table in MySQL first
select_query = "select * from predicted_outputs;"
cursor.execute(select_query)

0

In [31]:
# insert data from df_new_obs to predicted_outputs in MySQL

#insert query follows this format insert into ___ values (record), in which record = (value, value),
# and don't forget to end query with ; 
insert_query = 'insert into predicted_outputs values '
records_new_obs = df_new_obs.to_records(index=False)
records_new_obs

rec.array([(0, 0., 0, 1, 6, 179, 30, 19, 1, 0, 0, 0.12279926, 0),
           (1, 0., 0, 0, 6, 361, 28, 27, 0, 1, 4, 0.87339235, 1),
           (0, 0., 0, 1, 6, 155, 34, 25, 0, 2, 0, 0.26830495, 0),
           (0, 0., 0, 1, 6, 179, 40, 22, 1, 2, 0, 0.19638531, 0),
           (1, 0., 0, 0, 6, 155, 34, 25, 0, 2, 0, 0.72350172, 1),
           (1, 0., 0, 0, 6, 225, 28, 24, 0, 1, 2, 0.7168905 , 1),
           (1, 0., 0, 0, 6, 118, 46, 25, 0, 2, 0, 0.57052384, 1),
           (0, 0., 0, 1, 6, 179, 30, 19, 1, 0, 0, 0.12279926, 0),
           (0, 0., 0, 1, 6, 118, 37, 28, 0, 0, 0, 0.13411805, 0),
           (1, 0., 0, 0, 6, 118, 37, 28, 0, 0, 0, 0.52500656, 1),
           (0, 0., 0, 1, 6, 378, 36, 21, 0, 2, 4, 0.45499802, 0),
           (0, 0., 1, 0, 6, 118, 50, 31, 0, 1, 0, 0.64474164, 1),
           (0, 0., 1, 0, 6, 233, 31, 21, 1, 1, 8, 0.35110766, 0),
           (0, 0., 0, 1, 6, 179, 30, 19, 1, 0, 0, 0.12279926, 0),
           (0, 0., 0, 0, 6, 235, 48, 33, 0, 1, 5, 0.09653346, 0),
           (0, 0., 0, 0, 6, 268, 33, 25, 1, 0, 0, 0.18947859, 0),
           (0, 0., 1, 0, 6, 118, 50, 31, 0, 1, 0, 0.64474164, 1),
           (1, 0., 0, 0, 6, 179, 30, 19, 1, 0, 0, 0.49973827, 0),
           (0, 0., 0, 1, 6, 291, 40, 25, 0, 1, 1, 0.38953149, 0),
           (1, 0., 0, 0, 7, 179, 30, 19, 1, 0, 0, 0.50016122, 1),
           (0, 0., 0, 1, 7, 118, 37, 28, 0, 0, 0, 0.13431465, 0),
           (0, 0., 0, 1, 7, 233, 31, 21, 1, 1, 8, 0.05136656, 0),
           (1, 0., 0, 0, 7, 118, 37, 28, 0, 0, 0, 0.52542844, 1),
           (1, 0., 0, 0, 7, 118, 37, 28, 0, 0, 0, 0.52542844, 1),
           (0, 0., 0, 1, 7, 233, 31, 21, 1, 1, 8, 0.05136656, 0),
           (0, 0., 0, 1, 7, 235, 43, 38, 0, 1, 0, 0.51235187, 1),
           (0, 0., 1, 0, 7, 233, 31, 21, 1, 1, 8, 0.3514932 , 0),
           (1, 0., 0, 0, 7, 228, 58, 22, 0, 2, 1, 0.63338494, 1),
           (0, 0., 0, 1, 7, 118, 37, 28, 0, 0, 0, 0.13431465, 0),
           (1, 0., 0, 0, 7, 228, 58, 22, 0, 2, 1, 0.63338494, 1),
           (0, 0., 0, 1, 7, 189, 33, 25, 0, 2, 2, 0.24494274, 0),
           (0, 0., 0, 1, 7, 118, 37, 28, 0, 0, 0, 0.13431465, 0),
           (0, 0., 0, 1, 7, 361, 28, 27, 0, 1, 4, 0.49196214, 0),
           (0, 0., 0, 1, 7, 225, 28, 24, 0, 1, 2, 0.26224033, 0),
           (1, 0., 0, 0, 7, 369, 31, 25, 0, 3, 0, 0.96656016, 1),
           (1, 0., 0, 0, 7, 289, 33, 30, 0, 2, 1, 0.91239892, 1),
           (1, 0., 0, 0, 7, 235, 37, 29, 1, 1, 1, 0.74659759, 1),
           (0, 0., 0, 0, 7, 118, 40, 34, 0, 1, 8, 0.0230895 , 0),
           (0, 0., 0, 0, 7, 231, 39, 35, 0, 2, 2, 0.29564749, 0),
           (0, 0., 0, 0, 7, 179, 53, 25, 0, 1, 1, 0.07644957, 0)],
          dtype=[('Reason_1', 'u1'), ('Reason_2', '<f8'), ('Reason_3', 'u1'), ('Reason_4', 'u1'), ('Month Value', '<i8'), ('Transportation Expense', '<i8'), ('Age', '<i8'), ('Body Mass Index', '<i8'), ('Education', '<i8'), ('Children', '<i8'), ('Pet', '<i8'), ('Probability', '<f8'), ('Prediction', '<i4')])

In [32]:
for record in records_new_obs: 
    row = str(record)
    insert_query += row + ','

#remove the last , after the loop operation
insert_query = insert_query[:-1] + ";"
insert_query

'insert into predicted_outputs values (0, 0., 0, 1, 6, 179, 30, 19, 1, 0, 0, 0.12279926, 0),(1, 0., 0, 0, 6, 361, 28, 27, 0, 1, 4, 0.87339235, 1),(0, 0., 0, 1, 6, 155, 34, 25, 0, 2, 0, 0.26830495, 0),(0, 0., 0, 1, 6, 179, 40, 22, 1, 2, 0, 0.19638531, 0),(1, 0., 0, 0, 6, 155, 34, 25, 0, 2, 0, 0.72350172, 1),(1, 0., 0, 0, 6, 225, 28, 24, 0, 1, 2, 0.7168905, 1),(1, 0., 0, 0, 6, 118, 46, 25, 0, 2, 0, 0.57052384, 1),(0, 0., 0, 1, 6, 179, 30, 19, 1, 0, 0, 0.12279926, 0),(0, 0., 0, 1, 6, 118, 37, 28, 0, 0, 0, 0.13411805, 0),(1, 0., 0, 0, 6, 118, 37, 28, 0, 0, 0, 0.52500656, 1),(0, 0., 0, 1, 6, 378, 36, 21, 0, 2, 4, 0.45499802, 0),(0, 0., 1, 0, 6, 118, 50, 31, 0, 1, 0, 0.64474164, 1),(0, 0., 1, 0, 6, 233, 31, 21, 1, 1, 8, 0.35110766, 0),(0, 0., 0, 1, 6, 179, 30, 19, 1, 0, 0, 0.12279926, 0),(0, 0., 0, 0, 6, 235, 48, 33, 0, 1, 5, 0.09653346, 0),(0, 0., 0, 0, 6, 268, 33, 25, 1, 0, 0, 0.18947859, 0),(0, 0., 1, 0, 6, 118, 50, 31, 0, 1, 0, 0.64474164, 1),(1, 0., 0, 0, 6, 179, 30, 19, 1, 0, 0, 0.49973827, 0),(0, 0., 0, 1, 6, 291, 40, 25, 0, 1, 1, 0.38953149, 0),(1, 0., 0, 0, 7, 179, 30, 19, 1, 0, 0, 0.50016122, 1),(0, 0., 0, 1, 7, 118, 37, 28, 0, 0, 0, 0.13431465, 0),(0, 0., 0, 1, 7, 233, 31, 21, 1, 1, 8, 0.05136656, 0),(1, 0., 0, 0, 7, 118, 37, 28, 0, 0, 0, 0.52542844, 1),(1, 0., 0, 0, 7, 118, 37, 28, 0, 0, 0, 0.52542844, 1),(0, 0., 0, 1, 7, 233, 31, 21, 1, 1, 8, 0.05136656, 0),(0, 0., 0, 1, 7, 235, 43, 38, 0, 1, 0, 0.51235187, 1),(0, 0., 1, 0, 7, 233, 31, 21, 1, 1, 8, 0.3514932, 0),(1, 0., 0, 0, 7, 228, 58, 22, 0, 2, 1, 0.63338494, 1),(0, 0., 0, 1, 7, 118, 37, 28, 0, 0, 0, 0.13431465, 0),(1, 0., 0, 0, 7, 228, 58, 22, 0, 2, 1, 0.63338494, 1),(0, 0., 0, 1, 7, 189, 33, 25, 0, 2, 2, 0.24494274, 0),(0, 0., 0, 1, 7, 118, 37, 28, 0, 0, 0, 0.13431465, 0),(0, 0., 0, 1, 7, 361, 28, 27, 0, 1, 4, 0.49196214, 0),(0, 0., 0, 1, 7, 225, 28, 24, 0, 1, 2, 0.26224033, 0),(1, 0., 0, 0, 7, 369, 31, 25, 0, 3, 0, 0.96656016, 1),(1, 0., 0, 0, 7, 289, 33, 30, 0, 2, 1, 0.91239892, 1),(1, 0., 0, 0, 7, 235, 37, 29, 1, 1, 1, 0.74659759, 1),(0, 0., 0, 0, 7, 118, 40, 34, 0, 1, 8, 0.0230895, 0),(0, 0., 0, 0, 7, 231, 39, 35, 0, 2, 2, 0.29564749, 0),(0, 0., 0, 0, 7, 179, 53, 25, 0, 1, 1, 0.07644957, 0);'

In [33]:
cursor.execute(insert_query)

40

In [34]:
conn.commit()

In [35]:
# now that we have loaded the data into the table, let's close the connection 
conn.close()